# Generated by Django 3.2.6 on 2021-08-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flamApp', '0002_alter_imagepro_color_transform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepro',
            name='color_transform',
            field=models.CharField(blank=True, choices=[('l', 'L'), ('rbg', 'RBG'), ('cmyk', 'CMYK (cyan, magenta, yellow, black)')], max_length=500, null=True),
        ),
    ]
