# Generated by Django 3.2.6 on 2021-08-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flamApp', '0003_alter_imagepro_color_transform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepro',
            name='color_transform',
        ),
    ]
