# Generated by Django 3.2.6 on 2021-08-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flamApp', '0004_remove_imagepro_color_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepro',
            name='dsfsd',
            field=models.CharField(blank=True, choices=[('flip left right', 'FLIP LEFT RIGHT'), ('flip top bottom', 'FLIP TOP BOTTOM')], max_length=500, null=True),
        ),
    ]
