# Generated by Django 3.2.6 on 2021-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flamApp', '0005_imagepro_dsfsd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepro',
            old_name='dsfsd',
            new_name='flip_to',
        ),
        migrations.AddField(
            model_name='imagepro',
            name='color_transform',
            field=models.CharField(blank=True, choices=[('l', 'L'), ('rbg', 'RBG'), ('cmyk', 'CMYK (cyan, magenta, yellow, black)')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imagepro',
            name='rotate_by',
            field=models.CharField(blank=True, choices=[('rotate 90', 'ROTATE 90'), ('rotate 180', 'ROTATE 180'), ('rotate 270', 'ROTATE 270')], max_length=500, null=True),
        ),
    ]
